// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  KV: KVNamespace;
  APP_DOMAIN: "auto-yt-notify.blankparticle.in";
  API_SECRET: string;
  DISCORD_WEBHOOK_URL: string;
}
