#:schema node_modules/wrangler/config-schema.json
name = "auto-yt-notify"
main = "src/index.ts"
compatibility_date = "2024-10-22"
routes = [{ pattern = "auto-yt-notify.blankparticle.in", custom_domain = true }]

[vars]
APP_DOMAIN = "auto-yt-notify.blankparticle.in"

[[kv_namespaces]]
binding = "KV"
id = "156eb30bd7b64bb2be0c16caea81cfdf"

[triggers]
crons = ["0 0 */3 * *"]
